### ISSUE TITLE
No sample data

### ISSUE THREAD

**Issue by ghost** [djjudas21/photodb-perl#1]
Hi There,

It appears there's no sample data in any of the files. Should it be or did the blurb about it in the ReadMe just need to be removed?

Thanks!

**Comment by djjudas21** [comment]
Hi there,

Well spotted - there should be sample data in some of the tables. I could have sworn the script `dump-schema.sql` handled this but looking at the code, it only dumps the schema.

Leave it with me, I'll try and find a way of repeatably exporting the sample data in some of the tables from my live instance.

Cheers,
Jonathan

**Comment by djjudas21** [comment]
I added a new script for dumping sample data from some tables (c0a0b262bee506b063459260b306bdc46a773d6a) and then I added the sample data itself (8f583cee5b01c1b737d7a8a814e91d1fc8f32973).

Hope this helps!
Jonathan

**Comment by ghost** [comment]
Thanks! It worked great for me. :)
